name = "FFTGrp"
uuid = "bf06c732-83f0-403e-9c22-2c4c46823249"
authors = ["Naoki Maeda2 <fnkyksj@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
